class ZarfilmError(Exception): ...
class AuthError(ZarfilmError): ...
class SessionExpiredError(AuthError): ...
class NotFoundError(ZarfilmError): ...
class ParseError(ZarfilmError): ...


class SubdlError(Exception):
    """SubDL API failure (missing/invalid key, quota, bad answer).

    Deliberately outside the ZarfilmError tree: subtitles have their own source
    and their own credentials, so a SubDL outage must never look like an expired
    zarfilm session. Messages never carry the API key or the request URL.
    """
